# Generated by Django 4.0.3 on 2022-03-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_model',
            field=models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1),
        ),
    ]
